-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.course
(
    id serial NOT NULL,
    title character varying(128) COLLATE pg_catalog."default" NOT NULL,
    instructor_id integer NOT NULL,
    CONSTRAINT course_pkey PRIMARY KEY (id),
    CONSTRAINT course_title_key UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS public.instructor
(
    id serial NOT NULL,
    first_name character varying(45) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    last_name character varying(45) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    email character varying(45) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    instructor_detail_id integer,
    CONSTRAINT instructor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.instructor_detail
(
    id serial NOT NULL,
    youtube_channel character varying(128) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    hobby character varying(45) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    CONSTRAINT instructor_detail_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.course
    ADD CONSTRAINT course_instructor_id_fkey FOREIGN KEY (instructor_id)
    REFERENCES public.instructor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.instructor
    ADD CONSTRAINT fk_instructor_detail FOREIGN KEY (instructor_detail_id)
    REFERENCES public.instructor_detail (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;











-- Add instructor details
INSERT INTO public.instructor_detail (youtube_channel, hobby)
VALUES 
('https://youtube.com/channel/taro_yamada', 'Karate'),  -- 山田 太郎 (Yamada Taro)
('https://youtube.com/channel/hanako_tanaka', 'Sado'),  -- Tea Ceremony (茶道)
('https://youtube.com/channel/ichiro_suzuki', 'Judo'),  -- 柔道 (Judo)
('https://youtube.com/channel/sachiko_kato', 'Ikebana'), -- Flower Arrangement (生け花)
('https://youtube.com/channel/shinji_takahashi', 'Shogi'); -- 将棋 (Japanese Chess)

-- Add instructors with Japanese names in Romaji
INSERT INTO public.instructor (first_name, last_name, email, instructor_detail_id)
VALUES
('Taro', 'Yamada', 'taro.yamada@example.com', 1),    -- 山田 太郎
('Hanako', 'Tanaka', 'hanako.tanaka@example.com', 2), -- 田中 花子
('Ichiro', 'Suzuki', 'ichiro.suzuki@example.com', 3), -- 鈴木 一郎
('Sachiko', 'Kato', 'sachiko.kato@example.com', 4),   -- 加藤 幸子
('Shinji', 'Takahashi', 'shinji.takahashi@example.com', 5); -- 高橋 伸二

-- Add courses and link them to instructors
INSERT INTO public.course (title, instructor_id)
VALUES
('Suugaku 101', 1),     -- Mathematics by 山田 太郎
('Butsurigaku 202', 1), -- Physics by 山田 太郎
('Bijutsushi', 2),      -- Art History by 田中 花子
('Kagaku 101', 3),      -- Chemistry by 鈴木 一郎
('Seibutsugaku 101', 3),-- Biology by 鈴木 一郎
('Rekishi 101', 4),     -- History by 加藤 幸子
('Shinrigaku', 5),      -- Psychology by 高橋 伸二
('Keizaigaku', 5),      -- Economics by 高橋 伸二
('Tetsugaku', 4),       -- Philosophy by 加藤 幸子
('Informatics', 2);     -- Informatics by 田中 花子